---
- name: Setup nginx Docker container
  hosts: localhost
  vars:
    nginx_config_path: "../nginx/nginx.conf"
    index_html_path: "../index.html"

  tasks:
    - name: Ensure nginx Docker container is running
      docker_container:
        name: nginx_container
        image: nginx
        state: started
        restart_policy: always
        ports:
          - "8081:80"
        volumes:
          - "{{ nginx_config_path }}:/etc/nginx/conf.d/default.conf"
          - "{{ index_html_path }}:/usr/share/nginx/html/index.html"
