version: "3.8"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    environment:
      GF_SECURITY_ADMIN_USER: user
      GF_SECURITY_ADMIN_PASSWORD: password
    ports:
      - 3000:3000
    volumes:
      - grafana_storage:/var/lib/grafana
      - grafana_data_sources:/etc/grafana/datasources
      - grafana_dashboards:/etc/grafana/dashboards
      - grafana_plugins:/var/lib/grafana/plugins

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus
      - prometheus_data:/prometheus

volumes:
  grafana_storage:
  grafana_data_sources:
  grafana_dashboards:
  grafana_plugins:
  prometheus_data:
